version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./backend/public:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
    networks:
      - app-network
  
  web:
    build:
      context: ./docker
      dockerfile: Dockerfile.backend
    container_name: php
    volumes:
      - ./backend/public:/var/www/html
      - ./backend:/var/www
    networks:
      - app-network

  frontend:
    image: node:20
    container_name: frontend
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev -- --host"
    ports:
      - "5173:5173"
    networks:
      - app-network 
  db:
    image: mysql:8.0
    container_name: controlacademico-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: control_academico
      MYSQL_USER: usuario
      MYSQL_PASSWORD: usuario123
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: controlacademico-pma
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=rootpassword
    depends_on:
      - db
    networks:
      - app-network

networks:
   app-network:

volumes:
  db_data:
